logging:
  level:
    root: INFO
    org:
      springframework: DEBUG
      
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://ours.auth.kc:30300/realms/OurApplicationRealm
          jwk-set-uri: http://ours.auth.kc:30300/realms/OurApplicationRealm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: our-application
            client-secret: XvTYsDYHY4SoQxHZpG6aY97gOcG48XKq
            scope:
            - openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/our-application
        provider: 
          keycloak:
            issuer-uri: http://ours.auth.kc:30300/realms/OurApplicationRealm
            user-name-attribute: preferred_username 
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: "ours.auth.kc"
          keystore:
            location: "classpath:ssl/keystore.jks"
            password: changeit
            type: "JKS"                     
 
  main:
    allow-bean-definition-overriding: true      
        
server:
  error:
    whitelabel:
      enabled: false
