version: '3'

services:

  openldap:
    image: bitnami/openldap:2
    container_name: openldap
    hostname: openldap
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=ldapAdmin
      - LDAP_ROOT=dc=autorite,dc=gouv,dc=fr
      - LDAP_USER_DC=people
      - LDAP_GROUP=eapostilles
      - LDAP_SKIP_DEFAULT_TREE=yes
    volumes:
      - 'openldap_data:/bitnami/openldap'
    networks:
      idp-network:
        ipv4_address: 172.31.0.2
      
volumes:
  openldap_data:

networks:
  idp-network:
    external: true
  
    