version: '3'
services:
  postgresql4oidc:
    image: docker.io/bitnami/postgresql:11
    container_name: postgresql4oidc
    hostname: postgresql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=kc-oidc
      - POSTGRESQL_DATABASE=oidc
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - oidc-idp-network

  keycloak-oidc:
    container_name: kc-oidc
    hostname: oidc.auth.kc
    image: docker.io/bitnami/keycloak:21
    environment:
      - KEYCLOAK_HTTP_PORT=30100
      - KEYCLOAK_HTTPS_PORT=30103
      - KEYCLOAK_DATABASE_HOST=postgresql4oidc
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=oidc
      - KEYCLOAK_DATABASE_USER=kc-oidc
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloakAdmin
    depends_on:
      - postgresql4oidc
    ports:
      - "30100:30100"
    networks:
      oidc-idp-network:
      idp-network:
        ipv4_address: 172.31.0.4
    extra_hosts:
      ours.auth.kc: 172.31.0.3
      oidc.auth.kc: 172.31.0.4
    volumes:
      - './theme/oidc-theme:/opt/bitnami/keycloak/themes/oidc-theme'

volumes:
  postgresql_data:

networks:
  oidc-idp-network:
  idp-network:
    external: true